name: CI test build

on:
  push:
      branches:
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.*

    - name: Get current time
      uses: MyJetTools/get-current-time@v2
      id: current-time
      with:
        format: YYYY-MM-DD HH:mm:ss
        utcOffset: "+00:00"
        
    - name: Build
      run: dotnet build --configuration Release /p:AssemblyVersion=0.0.${{ github.run_number }}
    - name: Test
      run: dotnet test --no-build --configuration Release
    - name: ls
      run: ls

    - name: Publish Service API
      run: dotnet publish --no-build ./src/Service.BonusCampaign/Service.BonusCampaign.csproj --configuration Release --output ./publish-api
 
    - name: Publish Service Worker
      run: dotnet publish --no-build ./src/Service.BonusCampaign.Worker/Service.BonusCampaign.Worker.csproj --configuration Release --output ./publish-worker

    - name: Check Service dir API
      run: ls ./publish-api
    
    - name: Check Service dir Worker
      run: ls ./publish-worker
            
    - name: Publish image API
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-api
        registry: docker.pkg.github.com
        repository: ${{ secrets.ORG_NAME }}/service.bonuscampaign/myjetwallet.service.bonuscampaign-test
        tags: latest
        build_args: app_version=myjetwallet.service.bonuscampaign-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: Publish image Worker
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        path: ./publish-worker
        registry: docker.pkg.github.com
        repository: ${{ secrets.ORG_NAME }}/service.bonuscampaign/myjetwallet.service.bonuscampaign.worker-test
        tags: latest
        build_args: app_version=myjetwallet.service.bonuscampaign.worker-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: Publish image ST API
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: ./publish-api
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: spot/myjetwallet.service.bonuscampaign-test
        tags: latest
        add_git_labels: true
        build_args: app_version=myjetwallet.service.bonuscampaign-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

    - name: Publish image ST Worker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.ST_DOCKER_USER }}
        password: ${{ secrets.ST_DOCKER_PASSWORD }}
        path: ./publish-worker
        registry: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        repository: spot/myjetwallet.service.bonuscampaign.worker-test
        tags: latest
        add_git_labels: true
        build_args: app_version=myjetwallet.service.bonuscampaign.worker-test:latest,app_compilation_date=${{ steps.current-time.outputs.formattedTime }}

  restart:
    runs-on: self-hosted   
    needs: build
    steps:
    - name: Restart service
      uses: Myjetwallet/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA__ST_TEST }}
        NAMESPACE: ${{ secrets.KUBE_TEST_NAMESPACE }}
        POD: bonuscampaign

    - name: Restart Worker
      uses: Myjetwallet/kube-restart-pods@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA__ST_TEST }}
        NAMESPACE: ${{ secrets.KUBE_TEST_NAMESPACE }}
        POD: bonuscampaign-worker

